import type { CourseDetail } from "@/types";

// This file is the ONLY place course content lives today. Every page reads
// through lib/courses/repository.ts rather than importing this array
// directly — so when Module 0 (backend) and Module 12 (admin dashboard) are
// built, only the repository's implementation changes to query Supabase
// instead of this file. No page or component code will need to change.
export const coursesData: CourseDetail[] = [
  {
    slug: "spoken-english-master-course",
    name: "Spoken English Master Course",
    nameBn: "স্পোকেন ইংলিশ মাস্টার কোর্স",
    tagline: "Our flagship path from first sentence to fluent conversation.",
    icon: "🗣️",
    level: "All Levels",
    audience: ["Students", "College", "Professionals"],
    category: ["Speaking"],
    duration: "Basic (6 months) → Intermediate (1 year) → Advanced (2 years)",
    format: "Live",
    language: "Bilingual — Bengali & English",
    schedule: "Batches run through the week; timing confirmed at enrollment to suit your time zone.",
    overview:
      "Our most complete spoken English journey — three connected levels that take you from basic sentence-building to fluent, confident conversation, all taught with our bilingual, speaking-first method.",
    whoShouldJoin: [
      "Anyone starting from scratch who wants a complete, structured path",
      "Students who've studied English for years but still can't speak it",
      "Professionals who want fluency, not just exam grammar",
    ],
    eligibility: "No prior spoken English proficiency required — placement is honest and judgment-free.",
    syllabus: [
      "Foundational grammar and sentence construction",
      "Daily guided speaking practice",
      "Vocabulary building by real-life theme",
      "Conversation and real-world scenario practice",
    ],
    outcomes: [
      "Speak in complete, grammatically sound sentences",
      "Hold an everyday conversation without freezing",
      "Read and understand general English confidently",
      "A foundation strong enough to build any specialization on top of",
    ],
    weeklyPractice: "Structured speaking and grammar exercises assigned every week.",
    assignments: "Checked, purposeful assignments tied directly to that week's lesson.",
    mockTests: "Regular practice evaluations to catch gaps early.",
    certificateStatus: "coming-soon",
    featured: true,
  },
  {
    slug: "complete-english-grammar-mastery",
    name: "Complete English Grammar Mastery",
    nameBn: "সম্পূর্ণ ইংলিশ গ্রামার মাস্টারি",
    tagline: "Every grammar rule, explained bilingually, drilled through real examples.",
    icon: "📖",
    level: "All Levels",
    audience: ["Students", "College"],
    category: ["Grammar"],
    duration: "Self-paced core syllabus + live sessions",
    format: "Hybrid",
    language: "Bilingual — Bengali & English",
    schedule: "Live doubt-solving sessions weekly; core material available anytime.",
    overview:
      "A structured, rule-by-rule journey through English grammar — from tenses to complex sentence structure — explained in Bengali first, then anchored firmly in English.",
    whoShouldJoin: [
      "Students who know grammar rules but still make the same mistakes",
      "Anyone preparing for board or competitive exams",
      "Learners who were only ever taught grammar in English and stayed confused",
    ],
    eligibility: "Open to all levels — the syllabus is sequenced from foundational to advanced.",
    syllabus: [
      "Tenses, taught in the order they're actually used in speech",
      "Sentence structure, clauses, and common error patterns",
      "A running \"common mistakes Bengali speakers make\" correction log",
      "Applied grammar — using rules in real writing and speech, not just worksheets",
    ],
    outcomes: [
      "Stop translating grammar rules and start using them naturally",
      "Recognize and self-correct the most common Bengali-English error patterns",
      "Write and speak with structural confidence",
    ],
    weeklyPractice: "Themed grammar drills released weekly.",
    assignments: "Written exercises reviewed with corrective feedback.",
    mockTests: "Regular practice tests across every grammar topic covered.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "vocabulary-builder",
    name: "Vocabulary Builder",
    nameBn: "ভোকাবুলারি বিল্ডার",
    tagline: "Themed word lists and spaced repetition — words you'll actually use.",
    icon: "🔤",
    level: "All Levels",
    audience: ["Students", "College", "Professionals"],
    category: ["Vocabulary"],
    duration: "Self-paced with weekly practice sets",
    format: "Hybrid",
    language: "Bilingual — Bengali & English",
    schedule: "New themed word sets released weekly.",
    overview:
      "Vocabulary organized by real-life theme — travel, interviews, workplace, exams — with every word anchored in a full example sentence instead of an isolated list to memorize and forget.",
    whoShouldJoin: [
      "Anyone whose vocabulary feels smaller than their actual thinking",
      "Students preparing for exams with a vocabulary component",
      "Professionals who want sharper, more precise everyday English",
    ],
    eligibility: "Open to all levels.",
    syllabus: [
      "Theme-based word sets (not alphabetical lists)",
      "Every word taught inside a full example sentence",
      "Planned spaced-repetition review for long-term retention",
      "Bilingual meaning and English usage shown side by side",
    ],
    outcomes: [
      "A working vocabulary organized around real situations, not random lists",
      "Words that stick because you've seen them used, not just defined",
      "Faster, more precise expression in both speech and writing",
    ],
    weeklyPractice: "Themed word sets with usage exercises.",
    assignments: "Sentence-writing tasks using newly learned words.",
    mockTests: "Periodic vocabulary recall checks.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "pronunciation-accent-training",
    name: "Pronunciation & Accent Training",
    nameBn: "প্রোনানসিয়েশন ও অ্যাকসেন্ট ট্রেনিং",
    tagline: "Focused correction of the sounds Bengali speakers find hardest.",
    icon: "🎙️",
    level: "Intermediate",
    audience: ["Students", "Professionals", "Job Seekers"],
    category: ["Speaking"],
    duration: "Short-course intensive",
    format: "Live",
    language: "Bilingual — Bengali & English",
    schedule: "Live practice sessions, confirmed at enrollment.",
    overview:
      "Focused, judgment-free training on the specific sound patterns that make Bengali-accented English hard to follow for others — so you're understood clearly, without needing to erase your identity.",
    whoShouldJoin: [
      "Anyone who's been asked to \"repeat that\" one too many times",
      "Job seekers preparing for interviews or client-facing roles",
      "Students who want clearer, more confident spoken delivery",
    ],
    eligibility: "Basic conversational English recommended before joining.",
    syllabus: [
      "Listen-and-repeat drills targeting real Bengali-to-English sound gaps",
      "Stress, rhythm, and intonation patterns in natural speech",
      "Clarity-focused correction — not accent elimination",
      "Practice built into real conversation scenarios",
    ],
    outcomes: [
      "Clearer, more easily understood spoken English",
      "Confidence speaking without over-monitoring every word",
      "Awareness of your own common pronunciation patterns and how to adjust them",
    ],
    weeklyPractice: "Guided listen-and-repeat drills.",
    assignments: "Recorded practice with teacher feedback.",
    mockTests: "Periodic clarity and comprehension checks.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "spoken-english-for-beginners",
    name: "Spoken English for Beginners",
    nameBn: "বিগিনারদের জন্য স্পোকেন ইংলিশ",
    tagline: "Your very first steps — no prior knowledge assumed, ever.",
    icon: "🌱",
    level: "Beginner",
    audience: ["Students", "Children"],
    category: ["Speaking"],
    duration: "6 months",
    format: "Live",
    language: "Bilingual — Bengali & English",
    schedule: "Batches run through the week; timing confirmed at enrollment.",
    overview:
      "Built for absolute beginners — starting from simple words and sentences, with every explanation grounded in Bengali so nothing feels overwhelming.",
    whoShouldJoin: [
      "Anyone who has never really spoken English before",
      "Students who feel \"behind\" and want to start fresh, without shame",
      "Parents choosing a first English program for an older child or teen",
    ],
    eligibility: "None — this is specifically designed for a true beginner.",
    syllabus: [
      "Basic sentence construction and everyday vocabulary",
      "Simple, guided speaking practice from lesson one",
      "Foundational grammar, explained bilingually",
      "Confidence-building through low-pressure repetition",
    ],
    outcomes: [
      "Comfort speaking simple, correct English sentences",
      "A foundation ready for the Intermediate level",
      "Real confidence, not just theoretical knowledge",
    ],
    weeklyPractice: "Simple guided speaking exercises.",
    assignments: "Light, confidence-building practice tasks.",
    mockTests: "Gentle, low-pressure progress checks.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "advanced-spoken-english",
    name: "Advanced Spoken English",
    nameBn: "অ্যাডভান্সড স্পোকেন ইংলিশ",
    tagline: "Master English completely. Speak fluently, think in English.",
    icon: "🚀",
    level: "Advanced",
    audience: ["College", "Professionals", "Job Seekers"],
    category: ["Speaking"],
    duration: "2 years",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "Batches run through the week; timing confirmed at enrollment.",
    overview:
      "For learners who already speak reasonably well and want to go further — nuanced expression, complex conversation, and the shift from translating to truly thinking in English.",
    whoShouldJoin: [
      "Learners who've completed our Basic and Intermediate levels",
      "Confident speakers who want polish, nuance, and range",
      "Professionals preparing for senior, English-heavy roles",
    ],
    eligibility: "Intermediate-level spoken comfort recommended.",
    syllabus: [
      "Advanced conversation and debate practice",
      "Nuanced vocabulary and idiomatic expression",
      "Public speaking and presentation skills",
      "Personality development alongside language skill",
    ],
    outcomes: [
      "Genuine fluency — thinking in English, not translating",
      "Confidence in high-stakes conversations and presentations",
      "Career-ready communication skills",
    ],
    weeklyPractice: "Advanced conversation and debate sessions.",
    assignments: "Presentation and structured-argument tasks.",
    mockTests: "Comprehensive fluency evaluations.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "interview-english",
    name: "Interview English",
    nameBn: "ইন্টারভিউ ইংলিশ",
    tagline: "Speak with confidence in any interview, anywhere.",
    icon: "💼",
    level: "Intermediate",
    audience: ["College", "Job Seekers"],
    category: ["Interview", "Career"],
    duration: "Short-course intensive",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "Live sessions, confirmed at enrollment.",
    overview:
      "Focused preparation for the moment that matters most — the interview. Real questions, professional phrasing, and live mock-interview practice.",
    whoShouldJoin: [
      "Job seekers with an interview coming up",
      "Final-year college students entering the job market",
      "Anyone who freezes under interview pressure, regardless of actual ability",
    ],
    eligibility: "Basic conversational English recommended.",
    syllabus: [
      "Common interview questions and confident answer structures",
      "Professional phrasing and tone",
      "Body language and delivery alongside language",
      "Live, recorded mock interview practice with feedback",
    ],
    outcomes: [
      "A confident, structured approach to any interview question",
      "Reduced anxiety through repeated real practice",
      "Professional communication that reflects your actual ability",
    ],
    weeklyPractice: "Mock interview drills.",
    assignments: "Self-introduction and answer-structuring exercises.",
    mockTests: "Full live mock interviews with feedback.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "hotel-hospitality-english",
    name: "Hotel & Hospitality English",
    nameBn: "হোটেল ও হসপিটালিটি ইংলিশ",
    tagline: "Workplace English for hospitality and service careers.",
    icon: "🏨",
    level: "Intermediate",
    audience: ["Professionals", "Job Seekers"],
    category: ["Career"],
    duration: "Short-course intensive",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "Live sessions, confirmed at enrollment.",
    overview:
      "Practical English for hotel, restaurant, and guest-service roles — guest conversation, phone etiquette, and the vocabulary this specific industry actually uses.",
    whoShouldJoin: [
      "Hospitality and service-industry job seekers",
      "Current hospitality staff wanting stronger guest communication",
      "Anyone pursuing hospitality careers abroad",
    ],
    eligibility: "Basic conversational English recommended.",
    syllabus: [
      "Guest-facing conversation scenarios",
      "Phone and email etiquette for hospitality settings",
      "Industry-specific vocabulary and phrasing",
      "Handling complaints and requests professionally",
    ],
    outcomes: [
      "Confident, professional guest communication",
      "Industry-relevant vocabulary ready for real shifts",
      "Stronger prospects for hospitality roles, including abroad",
    ],
    weeklyPractice: "Guest-scenario role-play exercises.",
    assignments: "Written guest-communication tasks (emails, messages).",
    mockTests: "Scenario-based practice evaluations.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "corporate-english",
    name: "Corporate English",
    nameBn: "কর্পোরেট ইংলিশ",
    tagline: "Professional communication for the modern workplace.",
    icon: "🏢",
    level: "Advanced",
    audience: ["Professionals"],
    category: ["Career"],
    duration: "Short-course intensive",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "Live sessions, confirmed at enrollment.",
    overview:
      "Email writing, meeting participation, presentations, and everyday workplace conversation — English built for the corporate environment specifically.",
    whoShouldJoin: [
      "Working professionals in English-heavy corporate roles",
      "Anyone preparing for a promotion or client-facing responsibilities",
      "Teams wanting sharper, more confident workplace communication",
    ],
    eligibility: "Intermediate spoken and written English recommended.",
    syllabus: [
      "Professional email and report writing",
      "Meeting participation and presentation skills",
      "Everyday workplace conversation and small talk",
      "Cross-cultural communication awareness",
    ],
    outcomes: [
      "Confident participation in meetings and presentations",
      "Clear, professional written communication",
      "Communication that supports career advancement",
    ],
    weeklyPractice: "Workplace-scenario writing and speaking tasks.",
    assignments: "Real-format email and report exercises.",
    mockTests: "Presentation and communication evaluations.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "business-english",
    name: "Business English",
    nameBn: "বিজনেস ইংলিশ",
    tagline: "Negotiate, network, and communicate like a business professional.",
    icon: "📊",
    level: "Advanced",
    audience: ["Professionals"],
    category: ["Career"],
    duration: "Short-course intensive",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "Live sessions, confirmed at enrollment.",
    overview:
      "Beyond day-to-day workplace English — negotiation, networking, client relationships, and the language of business itself.",
    whoShouldJoin: [
      "Business owners and entrepreneurs communicating with English-speaking clients",
      "Professionals in sales, business development, or client relations",
      "Anyone building an international business network",
    ],
    eligibility: "Intermediate-to-advanced English recommended.",
    syllabus: [
      "Negotiation and persuasive communication",
      "Networking and relationship-building conversation",
      "Business writing — proposals, pitches, client communication",
      "Presenting ideas and numbers with confidence",
    ],
    outcomes: [
      "Confidence in high-stakes business conversations",
      "Stronger client and partner relationships through clearer communication",
      "Professional presence in English-speaking business contexts",
    ],
    weeklyPractice: "Negotiation and pitch-practice exercises.",
    assignments: "Business writing tasks (proposals, client emails).",
    mockTests: "Simulated negotiation and pitch evaluations.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "ielts-preparation",
    name: "IELTS Preparation",
    nameBn: "আইইএলটিএস প্রস্তুতি",
    tagline: "Coming soon — structured preparation for the IELTS exam.",
    icon: "📄",
    level: "Advanced",
    audience: ["Students", "College", "Job Seekers"],
    category: ["School", "Career"],
    duration: "To be announced",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "To be announced.",
    overview:
      "A dedicated IELTS preparation track is in planning. This page will be updated with full syllabus and schedule details once the program launches.",
    whoShouldJoin: [
      "Students and professionals planning to study or work abroad",
      "Anyone needing a certified English proficiency score",
    ],
    eligibility: "To be announced.",
    syllabus: ["Full syllabus to be announced when this program launches."],
    outcomes: ["To be announced."],
    weeklyPractice: "To be announced.",
    assignments: "To be announced.",
    mockTests: "To be announced.",
    certificateStatus: "coming-soon",
    comingSoon: true,
  },
  {
    slug: "pte-preparation",
    name: "PTE Preparation",
    nameBn: "পিটিই প্রস্তুতি",
    tagline: "Coming soon — structured preparation for the PTE Academic exam.",
    icon: "🖥️",
    level: "Advanced",
    audience: ["Students", "College", "Job Seekers"],
    category: ["School", "Career"],
    duration: "To be announced",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "To be announced.",
    overview:
      "A dedicated PTE Academic preparation track is in planning. This page will be updated with full syllabus and schedule details once the program launches.",
    whoShouldJoin: [
      "Students and professionals planning to study or migrate abroad",
      "Anyone needing a computer-based English proficiency score",
    ],
    eligibility: "To be announced.",
    syllabus: ["Full syllabus to be announced when this program launches."],
    outcomes: ["To be announced."],
    weeklyPractice: "To be announced.",
    assignments: "To be announced.",
    mockTests: "To be announced.",
    certificateStatus: "coming-soon",
    comingSoon: true,
  },
  {
    slug: "oet-preparation",
    name: "OET Preparation",
    nameBn: "ওইটি প্রস্তুতি",
    tagline: "Coming soon — English preparation for healthcare professionals.",
    icon: "🩺",
    level: "Advanced",
    audience: ["Professionals", "Job Seekers"],
    category: ["Career"],
    duration: "To be announced",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "To be announced.",
    overview:
      "A dedicated OET track for nurses, doctors, and other healthcare professionals is in planning. This page will be updated once the program launches.",
    whoShouldJoin: ["Healthcare professionals seeking OET certification to work abroad"],
    eligibility: "To be announced.",
    syllabus: ["Full syllabus to be announced when this program launches."],
    outcomes: ["To be announced."],
    weeklyPractice: "To be announced.",
    assignments: "To be announced.",
    mockTests: "To be announced.",
    certificateStatus: "coming-soon",
    comingSoon: true,
  },
  {
    slug: "madhyamik-english",
    name: "Madhyamik English",
    nameBn: "মাধ্যমিক ইংলিশ",
    tagline: "100% free board-exam English mastery for Class 10 students.",
    icon: "🎓",
    level: "Intermediate",
    audience: ["Children", "Students"],
    category: ["School", "Grammar"],
    duration: "Aligned to the board exam schedule",
    format: "Live",
    language: "Bilingual — Bengali & English",
    schedule: "Batches run through the week; timing confirmed at enrollment.",
    overview:
      "A complete, 100% free English program built specifically for Madhyamik (Class 10) students — grammar, writing, and exam strategy, taught with genuine care.",
    whoShouldJoin: ["Every Madhyamik (Class 10) student — regardless of financial background"],
    eligibility: "Currently enrolled in, or preparing for, the Madhyamik (Class 10) board exam.",
    syllabus: [
      "Complete grammar syllabus, A to Z",
      "Seen and unseen passage practice",
      "Board-pattern writing practice",
      "Exam strategy and time management",
    ],
    outcomes: [
      "Strong, confident board-exam English performance",
      "Real grammar understanding, not just memorized answers",
      "A foundation that carries into Higher Secondary and beyond",
    ],
    weeklyPractice: "Board-pattern practice sets released weekly.",
    assignments: "Checked writing and grammar assignments.",
    mockTests: "Regular board-pattern test practice.",
    certificateStatus: "coming-soon",
    featured: true,
    free: true,
  },
  {
    slug: "hs-english",
    name: "HS English",
    nameBn: "উচ্চ মাধ্যমিক ইংলিশ",
    tagline: "Higher Secondary English, built for real exam confidence.",
    icon: "📚",
    level: "Intermediate",
    audience: ["Students", "College"],
    category: ["School", "Grammar"],
    duration: "Aligned to the board exam schedule",
    format: "Live",
    language: "Bilingual — Bengali & English",
    schedule: "Batches run through the week; timing confirmed at enrollment.",
    overview:
      "Structured English preparation for Higher Secondary (Class 11–12) students — building on Madhyamik-level grammar toward more advanced comprehension and writing.",
    whoShouldJoin: ["Higher Secondary (Class 11–12) students preparing for board exams"],
    eligibility: "Currently enrolled in Higher Secondary studies.",
    syllabus: [
      "Advanced grammar and comprehension",
      "Essay and formal writing practice",
      "Seen and unseen passage analysis",
      "Board-pattern exam strategy",
    ],
    outcomes: [
      "Confident, exam-ready English skills",
      "Stronger writing and comprehension for higher studies ahead",
      "A bridge between board English and real-world fluency",
    ],
    weeklyPractice: "Board-pattern comprehension and writing sets.",
    assignments: "Essay and formal-writing assignments.",
    mockTests: "Regular board-pattern test practice.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "english-for-competitive-exams",
    name: "English for Competitive Exams",
    nameBn: "প্রতিযোগিতামূলক পরীক্ষার ইংলিশ",
    tagline: "English preparation for government and competitive entrance exams.",
    icon: "🏆",
    level: "Advanced",
    audience: ["Students", "Job Seekers"],
    category: ["School", "Career"],
    duration: "Short-course intensive",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "Live sessions, confirmed at enrollment.",
    overview:
      "Focused English preparation for the kind of competitive and government exams many Bengali-speaking students take — comprehension, grammar accuracy, and vocabulary under time pressure.",
    whoShouldJoin: ["Students and job seekers preparing for competitive or government exams"],
    eligibility: "Intermediate English level recommended.",
    syllabus: [
      "Grammar accuracy under exam conditions",
      "Comprehension and vocabulary-in-context practice",
      "Time-management strategy for English sections",
      "Common competitive-exam question patterns",
    ],
    outcomes: [
      "Faster, more accurate performance on English sections",
      "Reduced exam-day anxiety through repeated practice",
      "A vocabulary and grammar base built for test conditions",
    ],
    weeklyPractice: "Timed practice sets.",
    assignments: "Exam-format grammar and comprehension exercises.",
    mockTests: "Timed mock sections mirroring real exam conditions.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "kids-english",
    name: "Kids English",
    nameBn: "কিডস ইংলিশ",
    tagline: "A joyful, confidence-first introduction to English for children.",
    icon: "🧒",
    level: "Beginner",
    audience: ["Children"],
    category: ["Speaking", "Vocabulary"],
    duration: "6 months",
    format: "Live",
    language: "Bilingual — Bengali & English",
    schedule: "Batches run through the week; timing confirmed at enrollment.",
    overview:
      "A gentle, game-based introduction to English for children — built around stories, play, and encouragement rather than pressure or memorization.",
    whoShouldJoin: ["Children beginning their English learning journey"],
    eligibility: "Designed for young learners; exact age guidance shared at enrollment.",
    syllabus: [
      "Basic vocabulary through stories and games",
      "Simple, encouraged speaking practice",
      "Foundational reading readiness",
      "Confidence and curiosity-building activities",
    ],
    outcomes: [
      "Comfort and curiosity around speaking English",
      "A joyful early foundation, not fear of the subject",
      "Readiness for more structured English learning ahead",
    ],
    weeklyPractice: "Playful, story-based practice activities.",
    assignments: "Light, engagement-focused home activities.",
    mockTests: "Gentle, encouragement-focused progress checks.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "english-for-homemakers",
    name: "English for Homemakers",
    nameBn: "গৃহিণীদের জন্য ইংলিশ",
    tagline: "Practical, everyday English — on a schedule that respects your day.",
    icon: "🏡",
    level: "Beginner",
    audience: ["Students"],
    category: ["Speaking"],
    duration: "6 months",
    format: "Live",
    language: "Bilingual — Bengali & English",
    schedule: "Flexible batch timing designed around a homemaker's daily schedule.",
    overview:
      "Practical, everyday spoken English — for conversations with children's schools, doctors, shopping, travel, and simply feeling confident in English-speaking spaces.",
    whoShouldJoin: ["Homemakers who want practical English for daily life, at a comfortable pace"],
    eligibility: "None — designed to start from wherever you are.",
    syllabus: [
      "Everyday conversation — home, school, market, travel",
      "Practical vocabulary for common daily situations",
      "Confidence-building speaking practice",
      "Basic grammar, explained simply and bilingually",
    ],
    outcomes: [
      "Comfort speaking English in everyday situations",
      "Confidence in settings like children's schools or clinics",
      "A foundation you can keep building on, at your own pace",
    ],
    weeklyPractice: "Everyday-scenario speaking practice.",
    assignments: "Light, practical conversation tasks.",
    mockTests: "Gentle, encouraging progress checks.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "english-for-working-professionals",
    name: "English for Working Professionals",
    nameBn: "কর্মজীবীদের জন্য ইংলিশ",
    tagline: "Fit fluency into a working schedule — practical, career-focused English.",
    icon: "💻",
    level: "Intermediate",
    audience: ["Professionals"],
    category: ["Career"],
    duration: "1 year",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "Evening and weekend batches designed around working hours.",
    overview:
      "Built for professionals balancing a full-time job — practical spoken and written English for the workplace, at a pace and schedule that respects your time.",
    whoShouldJoin: ["Working professionals who want fluency without disrupting their job"],
    eligibility: "Basic English comprehension recommended.",
    syllabus: [
      "Workplace conversation and everyday professional English",
      "Email and message writing",
      "Meeting and small-talk confidence",
      "Practical grammar review",
    ],
    outcomes: [
      "Confident everyday workplace communication",
      "Improved written professional English",
      "Fluency progress that fits around a full-time job",
    ],
    weeklyPractice: "Workplace-scenario practice, scheduled around working hours.",
    assignments: "Practical writing and speaking tasks.",
    mockTests: "Periodic progress evaluations.",
    certificateStatus: "coming-soon",
  },
  {
    slug: "english-for-international-job-seekers",
    name: "English for International Job Seekers",
    nameBn: "আন্তর্জাতিক চাকরিপ্রার্থীদের জন্য ইংলিশ",
    tagline: "Career-ready English for Bengali speakers job-hunting abroad.",
    icon: "🌍",
    level: "Advanced",
    audience: ["Job Seekers", "Professionals"],
    category: ["Career", "Interview"],
    duration: "Short-course intensive",
    format: "Live",
    language: "Bilingual instruction, English-majority practice",
    schedule: "Live sessions, timed to work across time zones.",
    overview:
      "Focused English preparation for Bengali speakers pursuing jobs abroad — resumes, interviews, workplace communication, and the confidence to compete internationally.",
    whoShouldJoin: [
      "Job seekers applying for roles in the Middle East, Europe, North America, or elsewhere abroad",
      "Professionals preparing for international recruitment processes",
    ],
    eligibility: "Intermediate spoken English recommended.",
    syllabus: [
      "Resume and cover letter English",
      "International interview practice",
      "Workplace communication across cultures",
      "Confidence for video and phone interviews",
    ],
    outcomes: [
      "Application materials that read professionally",
      "Interview confidence for international recruiters",
      "Communication skills built for a global workplace",
    ],
    weeklyPractice: "International interview and application practice.",
    assignments: "Resume, cover letter, and self-introduction tasks.",
    mockTests: "Full mock international interview sessions.",
    certificateStatus: "coming-soon",
  },
];
